config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, except: [:destroy, :create, :new] 
  resources :groups, except: [:destroy, :show] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages
  has_many :messaged_users, through: :messages, source: :user

  validates :name, presence: true, uniqueness: true

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :group
  validates :body_or_image, presence: {message: "メッセージもしくは画像を入力してください"}

  private
  def body_or_image
    body.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :validatable, password_length: 8..128

  validates :name, presence:  {message: "を入力してください"}, uniqueness: {message: "は既に他のユーザが使用しています"}
  validates :email, presence:  {message: "を入力してください"}, uniqueness: {message: "は既に他のユーザが使用しています"}

  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages
  has_many :messaged_groups, through: :messages, source: :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update]
  def index
    @groups = current_user.groups.includes(:messages)
  end
  def new
   @group = Group.new
  end

  def create
    @group = Group.new(create_group_params)
    # 自身をチェックしていない場合に自身をメンバー追加
    unless @group.user_ids.include?(current_user.id)
      @group.group_users.new(user_id: current_user.id, group_id: @group.id)
    end

    @group.save
    if @group.save
      redirect_to group_messages_path(@group.id), notice: "グループが作成されました！"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
     @group.update(update_params)
     #自身が含まれていない時に自身をメンバーに追加
     unless @group.user_ids.include?(current_user.id)
       @group.group_users.new(user_id: current_user.id, group_id: @group.id)
     end
     if @group.save
       redirect_to group_messages_path(@group.id), notice: "グループ情報が更新されました"
     else
       render 'edit'
     end
  end

  private
  def create_group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def update_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, :set_message
  def index

  end

  def create
    @message = current_user.messages.new(create_params)
    respond_to do |format|
    if @message.save
      format.html {redirect_to group_messages_path(@message.group), notice: "メッセージ送信成功"}
      format.json

    else
        flash.now[:alert] = 'メッセージもしくは画像を送信してください'
        render 'index'
    end
  end
  end

  private
  def create_params
    params.require(:message).permit(:body,:image).merge(group_id: params[:group_id])
  end

  def set_group
    @groups = current_user.groups.includes(:messages)
    @group = Group.find(params[:group_id])
  end

  def set_message
    @message = @group.messages.new
    @messages = @group.messages.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit

  end

  def update
    current_user.update(update_params)
    redirect_to :root, notice: "アカウントが更新されました"
  end

  def index
    @users = User.all
   respond_to do |format|
     format.html { redirect_to new_group_path }
     format.json
   end
 end

  private

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = @group.errors.count
        件のエラーが発生しました。
        %ul
        - @group.errors.full_messages.each do |msg|
          %li
            = msg
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :Name, class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力して下さい", class: "chat-group-form__input", id: "chat_group_name"

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name,'チャットメンバーを追加', class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{ placeholder: "検索するユーザー名を入力してください", autocomplete: "off" }
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      %ul#add-users
        %li.chat-group-member.clearfix
          %p.chat-group-member__name#candidate-users
          %input{value: current_user.id, type: 'hidden'}
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :"チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      %ul#add-users
        %li.chat-group-member.clearfix
          %p.chat-group-member__name#added-users
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  #edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8"}
  = render partial: "form" 

app/views/groups/index.html.haml
= render partial: "messages/chat-side"
.chat-main

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  #new_chat_group.new_chat_group
  = render partial: "form"
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")
  = yield

app/views/messages/_chat-main.html.haml
-# チャットメイン画面
.chat-main
 .chat-header
  .chat-header__group
   .chat-header__group__name
    = @group.name
   .chat-header__group--edit-btn
    = link_to "edit", edit_group_path(@group)
  .chat-header__group-member
   MEMBER:
   - @group.users.each do |user|
    = user.name

 .chat-body
  - @messages.each do |message|
   .chat-body__message-box{"data-message-id": "#{message.id}"}
    .chat-body__message-box__name
     = message.user.name
    .chat-body__message-box__date
     = message.created_at.strftime("%Y/%m/%d/ %H:%M:%S")
    .chat-body__message-box__body
     = message.body
     %br
     .chat-body__message-box__image
      = image_tag message.image_url(:thumb).to_s


 .chat-footer
  = form_for [@group, @message] do |f|
   .chat-footer__form#new_message
    = f.text_field :body, placeholder: "Type a message", id: "message_body"
    = f.label :image ,:" ", class: "icon fa fa-image"
    = f.file_field :image, id: "message_image"
   .chat-footer--submit
    = f.submit "Sent"

app/views/messages/_chat-side.html.haml
.chat-side
 .user
  .user__user-content
   .user__user-content__user-name
    = current_user.name
   %a.user__user-content--user-new{"href":"/groups/new"}
    %i.fa.fa-pencil-square-o
   %a.user__user-content--user-edit{"href":"/users/#{current_user.id}/edit"}
    %i.fa.fa-cog
 .groups-list
  - @groups.each do |group|
   = link_to group_messages_path(group.id) do
    .group-box
     .group-box__group-name
      = group.name
     .group-box__group-message
      - if group.messages.present?
       -if group.messages.last.body.present?
        = group.messages.last.body
       - else
        = "画像を送信しました"
      - else
       = "メッセージはまだありません"

app/views/messages/index.html.haml
= render partial: "messages/chat-side"

= render partial: "messages/chat-main"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'